# Generated by Django 4.0.4 on 2023-01-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('group_number', models.CharField(max_length=10)),
                ('started', models.DateField(blank=True)),
            ],
        ),
    ]
