# Generated by Django 4.1.5 on 2023-02-01 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student'},
        ),
    ]
