# Generated by Django 4.1.5 on 2023-03-02 13:01

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1)),
                ('content', ckeditor.fields.RichTextField()),
                ('deadline', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('bands', models.ManyToManyField(to='students.band')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['py'])])),
                ('link_to_git', models.URLField(blank=True, max_length=255, null=True)),
                ('stand_up', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('is_deadline', models.BooleanField(blank=True, default=False)),
                ('score', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1)),
                ('feedback', ckeditor.fields.RichTextField(blank=True)),
                ('is_checked', models.BooleanField(blank=True, default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.task')),
            ],
        ),
    ]
