# Generated by Django 4.1.5 on 2023-02-01 22:48

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_options'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['py'])])),
                ('stand_up', models.TextField(verbose_name=django.core.validators.MinLengthValidator(60))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_deadline', models.BooleanField(blank=True, default=False)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('score', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1)),
                ('feedback', ckeditor.fields.RichTextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.task')),
            ],
        ),
    ]
